layout_spectrum: 0.06810036
typography_spectrum: 0.3243728
color:
  saturation: 0.653963
  lightness: 0.3605538
  brandStrength: 0.3064516
  brandColors:
    - '#F2F2F2'
    - '#161616'
    - '#C6C6C6'
    - '#393939'
    - '#5C5C5C'
  rhythmicContrast: 0.3843485
name: Speedarm
